#!/bin/bash
#
# matcha project package
# Copyright 2023 Joker


if [[ -z $(ruby -v) ]]; then
    echo "please check ruby env"
fi

curren_dir=$(pwd)

version=$(ruby -e "require './version.rb'; puts matcha_version")




#环境清理
/usr/bin/rm -f

# 依赖安装
/usr/bin/bundler install

#gem 本地包
/usr/bin/bundler package

echo  matcha_version

main "$@"
