#!/bin/bash
#
# Brief description of your script
# Copyright 2023 Joker

################################################################
# map collection
declare -A map

function map_put() {
  local key=$1
  local value=$2
  map["$key"]="$value"
}

function map_get() {
  echo "${map["$1"]}"
}

function map_remove() {
  local key=$1
  map["$key"]=
  unset 'map["$key"]'
}

function map_keys() {
  echo "${!map[@]}"
}

function map_values() {
  echo "${map[@]}"
}

################################################################
# stack collection
stack=()

function stack_push {
  local item=$1
  stack=("$item" "${stack[@]}")
}

function stack_pop {
  stack=("${stack[@]:1}")
}

function stack_peek {
  echo "${stack[0]}"
}

function stack_is_empty {
  [ ${#stack[@]} -eq 0 ] && echo 0 || echo 1
}

function main() {
 :
}

main "$@"
