#!/bin/bash
#
# Test for file model
# Copyright 2023 Joker

exec_file="../../src/core/file/controller"
source ../../src/core/log/matcha_log


function main() {
  $exec_file -c file_test_dir
  if [[ $? = 0 ]]; then
    log_info "[TEST] file model test successful"
    rm -rf file_test_dir
  fi
}

main "$@"
